//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuhovTask.LanguageFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuhovTask.LanguageFiles.ru", typeof(ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to десятичной.
        /// </summary>
        internal static string _decimal {
            get {
                return ResourceManager.GetString("decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в.
        /// </summary>
        internal static string _in {
            get {
                return ResourceManager.GetString("in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to миллиард.
        /// </summary>
        internal static string billion {
            get {
                return ResourceManager.GetString("billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to восемь.
        /// </summary>
        internal static string eight {
            get {
                return ResourceManager.GetString("eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to восемьсот.
        /// </summary>
        internal static string eight_hundreds {
            get {
                return ResourceManager.GetString("eight hundreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to восемьнадцать.
        /// </summary>
        internal static string eighteen {
            get {
                return ResourceManager.GetString("eighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to восемьдесят.
        /// </summary>
        internal static string eighty {
            get {
                return ResourceManager.GetString("eighty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to одиннадцать.
        /// </summary>
        internal static string eleven {
            get {
                return ResourceManager.GetString("eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пятнадцать.
        /// </summary>
        internal static string fifteen {
            get {
                return ResourceManager.GetString("fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пятьдесят.
        /// </summary>
        internal static string fifty {
            get {
                return ResourceManager.GetString("fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пять.
        /// </summary>
        internal static string five {
            get {
                return ResourceManager.GetString("five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пятьсот.
        /// </summary>
        internal static string five_hundrets {
            get {
                return ResourceManager.GetString("five hundrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сорок.
        /// </summary>
        internal static string forty {
            get {
                return ResourceManager.GetString("forty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to четыре.
        /// </summary>
        internal static string four {
            get {
                return ResourceManager.GetString("four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to четыреста.
        /// </summary>
        internal static string four_hundreds {
            get {
                return ResourceManager.GetString("four hundreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to четырнадцать.
        /// </summary>
        internal static string fourteen {
            get {
                return ResourceManager.GetString("fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сто.
        /// </summary>
        internal static string hundred {
            get {
                return ResourceManager.GetString("hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенное значение не является последовательностью цифр..
        /// </summary>
        internal static string Input_string_is_not_a_sequence_of_digits_ {
            get {
                return ResourceManager.GetString("Input string is not a sequence of digits.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите число.
        /// </summary>
        internal static string Input_the_number {
            get {
                return ResourceManager.GetString("Input the number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to а.
        /// </summary>
        internal static string less_than_five {
            get {
                return ResourceManager.GetString("less than five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тысячи.
        /// </summary>
        internal static string less_than_five_thousands {
            get {
                return ResourceManager.GetString("less than five thousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to миллион.
        /// </summary>
        internal static string million {
            get {
                return ResourceManager.GetString("million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ов.
        /// </summary>
        internal static string more_than_five {
            get {
                return ResourceManager.GetString("more than five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to девять.
        /// </summary>
        internal static string nine {
            get {
                return ResourceManager.GetString("nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to девятьсот.
        /// </summary>
        internal static string nine__hundreds {
            get {
                return ResourceManager.GetString("nine  hundreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to девятнадцать.
        /// </summary>
        internal static string nineteen {
            get {
                return ResourceManager.GetString("nineteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to девяносто.
        /// </summary>
        internal static string ninety {
            get {
                return ResourceManager.GetString("ninety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to восьмиричной.
        /// </summary>
        internal static string octal {
            get {
                return ResourceManager.GetString("octal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to один.
        /// </summary>
        internal static string one {
            get {
                return ResourceManager.GetString("one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сто.
        /// </summary>
        internal static string one_hundred {
            get {
                return ResourceManager.GetString("one hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to одна тысяча.
        /// </summary>
        internal static string one_thousand {
            get {
                return ResourceManager.GetString("one thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to семь.
        /// </summary>
        internal static string seven {
            get {
                return ResourceManager.GetString("seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to семьсот.
        /// </summary>
        internal static string seven_hundreds {
            get {
                return ResourceManager.GetString("seven hundreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to семнадцать.
        /// </summary>
        internal static string seventeen {
            get {
                return ResourceManager.GetString("seventeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to семьдесят.
        /// </summary>
        internal static string seventy {
            get {
                return ResourceManager.GetString("seventy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шесть.
        /// </summary>
        internal static string six {
            get {
                return ResourceManager.GetString("six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шестьсот.
        /// </summary>
        internal static string six_hundreds {
            get {
                return ResourceManager.GetString("six hundreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шестнадцать.
        /// </summary>
        internal static string sixteen {
            get {
                return ResourceManager.GetString("sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шестьдесят.
        /// </summary>
        internal static string sixty {
            get {
                return ResourceManager.GetString("sixty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to системе исчисления.
        /// </summary>
        internal static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to десять.
        /// </summary>
        internal static string ten {
            get {
                return ResourceManager.GetString("ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число не соответствует Int64..
        /// </summary>
        internal static string The_number_cannot_fit_in_an_Int64_ {
            get {
                return ResourceManager.GetString("The number cannot fit in an Int64.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тринадцать.
        /// </summary>
        internal static string thirteen {
            get {
                return ResourceManager.GetString("thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тридцать.
        /// </summary>
        internal static string thirty {
            get {
                return ResourceManager.GetString("thirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тясяч.
        /// </summary>
        internal static string thousands {
            get {
                return ResourceManager.GetString("thousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to три.
        /// </summary>
        internal static string three {
            get {
                return ResourceManager.GetString("three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to триста.
        /// </summary>
        internal static string three_hundreds {
            get {
                return ResourceManager.GetString("three hundreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to двенадцать.
        /// </summary>
        internal static string twelve {
            get {
                return ResourceManager.GetString("twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to двадцать.
        /// </summary>
        internal static string twenty {
            get {
                return ResourceManager.GetString("twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to два.
        /// </summary>
        internal static string two {
            get {
                return ResourceManager.GetString("two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to двести.
        /// </summary>
        internal static string two_hundreds {
            get {
                return ResourceManager.GetString("two hundreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to две тысячи.
        /// </summary>
        internal static string two_thousands {
            get {
                return ResourceManager.GetString("two thousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ноль.
        /// </summary>
        internal static string zero {
            get {
                return ResourceManager.GetString("zero", resourceCulture);
            }
        }
    }
}
